name: Bug report
description: Something isn't working as expected
labels: ["bug"]
title: "[bug] <short summary>"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much info as you can.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the problem.
      placeholder: >
        When I run `eenv init`, it fails with ...
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce (ideally in a fresh repo).
      placeholder: |
        1. `cargo new test && cd test`
        2. create .env with FOO=bar
        3. run `eenv init`
        4. observe error
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Output / logs
      description: Console output with `--verbose` if relevant.
      render: text

  - type: input
    id: eenv_version
    attributes:
      label: EENV version
      description: Output of `eenv --version` or crate version in Cargo.lock.
      placeholder: "eenv 0.0.2"
    validations:
      required: true

  - type: input
    id: rustc_version
    attributes:
      label: rustc version
      description: Output of `rustc -V`.
      placeholder: "rustc 1.xx.x (hash yyyy-mm-dd)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (x86_64)
        - Linux (ARM)
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: env_layout
    attributes:
      label: Env file layout
      description: >
        Names of env files involved (e.g., `.env`, `.env.local`, etc.).
        Do NOT paste secrets. Redact values.
      render: text

  - type: textarea
    id: config
    attributes:
      label: Config snippets
      description: Relevant parts of `.eenv.settings.json`, `.gitignore`, or `eenv.config.json` (redacted).
      render: json

  - type: input
    id: hooks_path
    attributes:
      label: Git hooks path
      description: Output of `git rev-parse --git-path hooks` (for hook issues).
      placeholder: ".git/hooks"

  - type: input
    id: minimal_repo
    attributes:
      label: Minimal reproduction repo (optional)
      placeholder: "https://github.com/yourname/eenv-repro"

  - type: checkboxes
    id: checks
    attributes:
      label: Check all that apply
      options:
        - label: I searched existing issues
          required: true
        - label: I agree to follow the Code of Conduct
          required: true
