name: Feature request
description: Suggest an idea for EENV
labels: ["enhancement"]
title: "[feature] <short summary>"
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: >
        We need to place `.env*.enc` artifacts in a custom directory for CI...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the API/CLI UX. Include examples.
      placeholder: |
        New config in `.eenv.settings.json`:
        {
          "enc_output_dir": "secrets/"
        }
        CLI: `eenv init --enc-dir secrets/`
      render: json
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other approaches you considered.

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      options:
        - label: Might be a breaking change
        - label: Has security implications
        - label: Affects performance

  - type: textarea
    id: context
    attributes:
      label: Additional context / use cases
