name: Regression
description: Something worked in a previous version but not now
labels: ["bug", "regression"]
title: "[regression] <short summary>"
body:
  - type: input
    id: prev_version
    attributes:
      label: Last working version
      placeholder: "0.0.1"
    validations:
      required: true
  - type: input
    id: new_version
    attributes:
      label: Affected version
      placeholder: "0.0.2"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output / logs
      render: text
